# Generated by Django 4.2.11 on 2024-04-28 13:34

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descraption', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=clinic.models.image_upload)),
            ],
        ),
    ]
