# Generated by Django 4.1.7 on 2024-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_make_order_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
