# Generated by Django 4.2.11 on 2024-04-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_make_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_order',
            name='date',
        ),
    ]
