# Generated by Django 4.2.11 on 2024-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_make_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
