# Generated by Django 4.2.11 on 2024-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_make_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_order',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
