# Generated by Django 4.2.11 on 2024-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_make_order_avilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_order',
            name='avilable',
            field=models.DateField(auto_now_add=True),
        ),
    ]
