# Generated by Django 4.2.11 on 2024-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_make_order_avilable'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='hl',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
