# Generated by Django 4.2.11 on 2024-05-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_make_order_hl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_order',
            name='avilable',
        ),
    ]
