# Generated by Django 4.2.11 on 2024-05-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_list', to='clinic.doctor'),
            preserve_default=False,
        ),
    ]
