# Generated by Django 4.2.11 on 2024-05-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_make_order_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_order',
            name='hl',
        ),
    ]
