# Generated by Django 4.2.11 on 2024-05-04 15:59

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_category_make_order_more_descraption_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clinic.models.image_upload)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
